### ISSUE TITLE
time about train

### ISSUE THREAD

**Issue by GlitteringAu** [tienmanhptit1312/Disentangle-VAE-for-VC#2]
Hello，how long will the train running?,I run about 12 hours just for 80 epoches ,or when can I stop the running?

**Comment by v-manhlt3** [comment]
Hi, I trained the model for 1650 epochs. But I think that after 1000 epochs this model performs well on the voice conversion task.

**Comment by PeGunter** [comment]
> Hi, I trained the model for 1650 epochs. But I think that after 1000 epochs this model performs well on the voice conversion task.
Ok,Thank you for your timely reply.
