### ISSUE TITLE
Sample rate of audio for training

### ISSUE THREAD

**Issue by linhld0811** [tienmanhptit1312/Disentangle-VAE-for-VC#3]
Thanks for your public repo, I have a question: I trained some models for TTS task like tacotron2, fastspeech, hifigan... and it's almost use mel-spectrogram from wav with sr=22050Hz, so i wonder that did you try to train your model in that sample rate and what is quality of synthesized wav?!

**Comment by v-manhlt3** [comment]
I haven't trained my model with audio at sr=22kHz, but I guess the quality is not so much different compared to training with audio at sr=16kHz. So if you are interested in my model, give it a try to train it on 22kHz audio.

**Comment by linhld0811** [comment]
Thanks for your reply! I have another question for you:
1. Can you share the performance of your model when inference on GPU and CPU ( some metrics like RTF-real time factor)?!
2. Your model is built to transform mel-spectrogram from one speaker to another, it don't have any linguistic information. So can I use the this model to combine with other component like Tacotron2, fastspeech, ... and a vocoder like wavenet, waveglow, hifigan to build the TTS system with any languages?!
