### ISSUE TITLE
Do not backpropagate through style embedding when training?

### ISSUE THREAD

**Issue by ZiangLong** [tienmanhptit1312/Disentangle-VAE-for-VC#4]
Hi. I am confused by the `forward` function of `DisentangledVAE`. I wonder why you detach the style embeddings from the computational graph. I would appreciate your clarification. Please let me know if I misunderstood anything.

![图片](https://user-images.githubusercontent.com/41099881/139382617-d139de82-1475-44cf-acee-9e45c46c99f3.png)

**Comment by v-manhlt3** [comment]
The reason is that we feed two samples **x1** and **x2** into the same encoder, then the encoder should learn a common style representation for both **x1** and **x2**. If we don't detach **style_mu2** and **style_logvar2**, the encoder will be backpropagated twice which could lead to unstable training results.

**Comment by ZiangLong** [comment]
> 
> 
> The reason is that we feed two samples **x1** and **x2** into the same encoder, then the encoder should learn a common style representation for both **x1** and **x2**. If we don't detach **style_mu2** and **style_logvar2**, the encoder will be backpropagated twice which could lead to unstable training results.

Thanks for your reply. Are **style_mu1** and **style_mu2** close to each other after training? 
As far as I saw, the training does not penalize the difference between two style embeddings of the same speaker. It would be amazing to see if the style embeddings of two different sentences from the same person are closed to each other.

**Comment by v-manhlt3** [comment]
After training my model, speaker embeddings, which come from the same speaker and different utterances, are closer to one others and form a cluster. You can see the visualization of speaker embedding space in my paper, particularly, in the figure. 3.
