### ISSUE TITLE
Reproduce_issue 2

### ISSUE THREAD

**Issue by wpf89928** [tienmanhptit1312/Disentangle-VAE-for-VC#8]
hi, I tried the batch size 8, and obtained the model of epoch 1300. It still does not work...May I know from approximately what epochs the model can succeed in converting?

Btw, in the training.sh script, --style_cof appears twice.

For your convinience, I list the configuration I used as follows:

batch_size:8
hidden_size:"400"
speaker_size:4
latent_size:32
lr:0.0001
epochs:20000
no_cuda:false
dataset:"VCTK"
seed:1
log_interval:500
report_interval:50
sample_size:64
do_not_resume:false
normalize:false
beta_cof:0.1
mse_cof:10
kl_cof:10
style_cof:0.1
samples_length:128
alpha:0.01
dataset_fp:"datasets/VCTK_mel"
log_dir:"results_bs8"
src_spk:"VCTK-Corpus_wav16_p225"
trg_spk:"VCTK-Corpus_wav16_p226"
train:true
convert:false

This is the latest epoch info:
====> Epoch: 1346 Average loss: 1187.7294
recons loss1 epoch_1346: 201.34361554669906
recons loss2 epoch_1346: 201.35837986851598
recons loss1 hat epoch_1346: 198.02147375708228
recons loss2 hat epoch_1346: 198.03397934372362
Z1 KL loss epoch_1346: 75.65964660781998
Z2 kL loss epoch_1346: 75.63799599862314
Z Style KL epoch_1346: 0.0009613697808068078
kl coef:  10

Let me know if you need any other information. Thank you!

**Comment by 3030xx-stack** [comment]
I would like to know if you have solved this problem

**Comment by v-manhlt3** [comment]
Hi, I retrained my model and everything works well. Regarding the <mark>--style_cof<mark> appearing twice, you should set it "--style_cof=0.1". Furthermore, you should look at regenerated mels to evaluate the model.
