### ISSUE TITLE
Questions about Disentangle-VAE training

### ISSUE THREAD

**Issue by 3030xx-stack** [tienmanhptit1312/Disentangle-VAE-for-VC#9]
Hi, I am very interested in your work and decided to train this model. Btw, in the training.sh script, --style_cof appears twice. Which parameter should I choose? Not only that, in the training.sh script,  - -samples-length =128, but in your paper  it is 64. What should I do?

**Comment by v-manhlt3** [comment]
Hi,

You should set <mark>--style_cof=0.1</mark> and <mark>--sample_length=64</mark> as I mentioned in my paper
